### ISSUE TITLE
What is meaning of the "Ztrain"?

### ISSUE THREAD

**Issue by DormouseLi** [HaohanWang/CF#1]
Hello！I am confused about the meaning of "Ztrain" in the run.py. Can you take an example about the "corresponding labels of confounding factors" in the MNIST dataset?

**Comment by HaohanWang** [comment]
Hi, the MNIST dataset does not have these labels. 

Confounding factors refers to the features in the data that are statistically correlated with the labels (Y), but are not semantically/causally related to the labels. 

For example, in medical imaging, the different devices may generate images of different qualities, then if the data is not appropriately split, the image quality may be correlated with the labels and considered as an important feature by the models. 

In this case, the labels of confounding factors refer to the labels of the devices.

**Comment by DormouseLi** [comment]
I see. Thank you！
